const Dummydata = [
  {
    id: "1",
    title: "Run Into You",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-1.png", "/img/landscape/img-1.png"],
  },
  {
    id: "2",
    title: "Shazam",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-2.png", "/img/landscape/img-2.png"],
  },
  {
    id: "3",
    title: "Avatar",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-3.png", "/img/landscape/img-3.png"],
  },
  {
    id: "4",
    title: "Fast X",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-4.png", "/img/landscape/img-4.png"],
  },
  {
    id: "5",
    title: "Blue Lock",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-5.png", "/img/landscape/img-5.png"],
  },
  {
    id: "6",
    title: "Little Mermaid",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-6.png", "/img/landscape/img-6.png"],
  },
  {
    id: "7",
    title: "The Tomorrow War",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-7.png", "/img/landscape/img-7.png"],
  },
  {
    id: "8",
    title: "The Batman",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-8.png", "/img/landscape/img-12.png"],
  },
  {
    id: "9",
    title: "All of Us Are Dead",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-9.png", "/img/landscape/img-17.png"],
  },
  {
    id: "10",
    title: "A Man Called Otto",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-10.png", "/img/landscape/img-9.png"],
  },
  {
    id: "11",
    title: "Alice In Borderland",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-11.png", "/img/landscape/img-18.png"],
  },
  {
    id: "12",
    title: "Big Hero Six",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-12.png", "/img/landscape/img-10.png"],
  },
  {
    id: "13",
    title: "Missing",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-13.png", "/img/landscape/img-19.png"],
  },
  {
    id: "14",
    title: "Suzume",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-14.png", "/img/landscape/img-11.png"],
  },
  {
    id: "15",
    title: "Megan",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-15.png", "/img/landscape/img-20.png"],
  },
  {
    id: "16",
    title: "Quantummania",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-16.png", "/img/landscape/img-25.png"],
  },
  {
    id: "17",
    title: "Duty After School",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-17.png", "/img/landscape/img-17.png"],
  },
  {
    id: "18",
    title: "My Hero Academia",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-18.png", "/img/landscape/img-26.png"],
  },
  {
    id: "19",
    title: "Multiverse Of Madness",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-19.png", "/img/landscape/img-27.png"],
  },
  {
    id: "20",
    title: "Don't Look Up",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-20.png", "/img/landscape/img-31.png"],
  },
  {
    id: "21",
    title: "Black Adam",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-21.png", "/img/landscape/img-28.png"],
  },
  {
    id: "22",
    title: "The Devil All The Time",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-22.png", "/img/landscape/img-29.png"],
  },
  {
    id: "23",
    title: "Ted Lasso",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-23.png", "/img/landscape/img-30.png"],
  },
  {
    id: "24",
    title: "Stuart Little",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-24.png", "/img/landscape/img-13.png"],
  },
  {
    id: "25",
    title: "Jurassic World",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-25.png", "/img/landscape/img-21.png"],
  },
  {
    id: "26",
    title: "Baymax",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-26.png", "/img/landscape/img-10.png"],
  },
  {
    id: "27",
    title: "Dilan 1991",
    genre: ["Misteri", "Fantasi", "Kriminal"],
    age: "16+",
    episode: "16",
    img: ["/img/potrait/img-27.png", "/img/landscape/img-22.png"],
  },
];

export default Dummydata;
